version: '3.8'

services:
  #Base de datos PostgreSQL
  #db:
   # image: postgres:15
    #container_name: erp_db
    #restart: always
    #environment:
     # POSTGRES_USER: postgres
     # POSTGRES_PASSWORD: postgres
     # POSTGRES_DB: erp
    #ports:
     # - "5433:5432"
    #volumes:
     # - postgres_data:/var/lib/postgresql/data
    #healthcheck:
     # test: ["CMD-SHELL", "pg_isready -U postgres"]
     # interval: 5s
     # timeout: 5s
     # retries: 5

  #Aplicacion FASTAPI
  app:
    build: .
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@host.docker.internal:5432/erp
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: "True"
      APP_NAME: "BACKEND"
    #depends_on: (se quita esto porque se va a usar DB local)
     # db:
      #  condition: service_healthy
    volumes:
      - ./app:/app/app #para desarrollo: cambios en tiempo real
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
